// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IFetcher is an autogenerated mock type for the IFetcher type
type IFetcher struct {
	mock.Mock
}

// FetchChildURLs provides a mock function with given fields: url
func (_m *IFetcher) FetchChildURLs(url string) ([]string, error) {
	ret := _m.Called(url)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchRobotsTxt provides a mock function with given fields: u
func (_m *IFetcher) FetchRobotsTxt(u string) string {
	ret := _m.Called(u)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewIFetcher creates a new instance of IFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFetcher(t mockConstructorTestingTNewIFetcher) *IFetcher {
	mock := &IFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
