// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	queue "monzo-crawler/pkg/queue"

	mock "github.com/stretchr/testify/mock"
)

// IWriter is an autogenerated mock type for the IWriter type
type IWriter struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IWriter) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: _a0
func (_m *IWriter) Write(_a0 queue.Element) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(queue.Element) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIWriter interface {
	mock.TestingT
	Cleanup(func())
}

// NewIWriter creates a new instance of IWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIWriter(t mockConstructorTestingTNewIWriter) *IWriter {
	mock := &IWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
